language: swift
osx_image: xcode9.4
script:
- xcodebuild -workspace SpeechRecognizerButton.xcworkspace -scheme Example -destination "platform=iOS Simulator,name=iPhone 7,OS=11.4" -configuration Debug -enableCodeCoverage YES clean build test
after_success:
- bash <(curl -s https://codecov.io/bash)
